### ISSUE TITLE
모두함께 pip uninstall chdp를 합시다!

### ISSUE THREAD

**Issue by dfdddfd** [kiki7000/chdp#5]
chdp 쓰레기니 Dpy를 배웁시다
모두함께 pip uninstall chdp를 합시다!

**Comment by kiki7000** [comment]
깃허브에서는 이러지 맙시다.....

**Comment by dfdddfd** [comment]
엌엌 ㅈㅅ

**Comment by kiki7000** [comment]
--스스로 CHDP가 쓰레기인건 인정하지만-- 굳이 소스코드 있는데 이거를 박제할 필요가 있는지....
