### ISSUE TITLE
chdp 엄청 오류천국

### ISSUE THREAD

**Issue by dfdddfd** [kiki7000/chdp#8]
chdp가 오류를 내뿜어요 고쳐주세요

**Comment by dfdddfd** [comment]
또 KDD에 다시 들어와주세요
이번에는 chdp 쓰지말고 dpy쓰세요

**Comment by kiki7000** [comment]
강좌 커찮고

**Comment by kiki7000** [comment]
님아 어떤 부분에서 무슨 오류가 나는지 말해야 고치죠

**Comment by kiki7000** [comment]
글고 chdp 서비스 나중에 종료하고 더 멋진걸로 찾아올테니까 강좌 보지 말라 하고 chdp 버리셈

**Comment by dfdddfd** [comment]
헐
