### ISSUE TITLE
What's advantage of chdp than Cogs?

### ISSUE THREAD

**Issue by TetraTheta** [kiki7000/chdp#9]
I felt too hard to code in `discord.ext.commands.Cogs` and I found this repository. Can you tell what would be benificial to use `chdp` than `discord.ext.commands.Cogs`?

I like the idea of 'Shoving everything related to that command into one file' but Cogs are so hard to me. I hope `chdp` would be much easier to manage...

**Comment by kiki7000** [comment]
I can't say chdp has more functions or chdp is easier than Cogs and there are no docs in chdp so I recommend using Cogs. But if you can analyze the code and create a bot using chdp, chdp could be more comfortable than Cogs.
: If you are a discord.py starter, use Cogs by asking your friend, etc.
